In [1]:
# Data handling
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Preprocessing
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split

# Models
from sklearn.linear_model import LogisticRegression
from sklearn.cluster import KMeans

# Evaluation
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
# Load dataset
df = pd.read_csv("AdvancedFitness.csv")

# Preview
df.head()

    created_utc  ...  distinguished
0  1.373374e+09  ...            NaN
1  1.350073e+09  ...            NaN
2  1.359465e+09  ...            NaN
3  1.323376e+09  ...            NaN
4  1.304022e+09  ...            NaN

[5 rows x 22 columns]

In [3]:
print(df.info())
print(df.describe())

# Check missing values
print(df.isnull().sum())

<class 'pandas.DataFrame'>
RangeIndex: 877 entries, 0 to 876
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   created_utc             877 non-null    float64
 1   score                   877 non-null    int64
 2   domain                  877 non-null    str
 3   id                      877 non-null    str
 4   title                   877 non-null    str
 5   author                  810 non-null    str
 6   ups                     877 non-null    int64
 7   downs                   877 non-null    int64
 8   num_comments            877 non-null    int64
 9   permalink               877 non-null    str
 10  selftext                547 non-null    str
 11  link_flair_text         0 non-null      float64
 12  over_18                 877 non-null    bool
 13  thumbnail               877 non-null    str
 14  subreddit_id            877 non-null    str
 15  edited                  877 non-null    str
 16  link_flair_css_class    0 non-null      float64
 17  author_flair_css_class  0 non-null      float64
 18  is_self                 877 non-null    bool
 19  name                    877 non-null    str
 20  url                     877 non-null    str
 21  distinguished           22 non-null     str
dtypes: bool(2), float64(4), int64(4), str(12)
memory usage: 1.3 MB
None
        created_utc       score  ...  link_flair_css_class  author_flair_css_class
count  8.770000e+02  877.000000  ...                   0.0                     0.0
mean   1.340290e+09   20.973774  ...                   NaN                     NaN
std    2.431996e+07   27.852441  ...                   NaN                     NaN
min    1.294768e+09    0.000000  ...                   NaN                     NaN
25%    1.315885e+09    8.000000  ...                   NaN                     NaN
50%    1.345493e+09   16.000000  ...                   NaN                     NaN
75%    1.361248e+09   28.000000  ...                   NaN                     NaN
max    1.376636e+09  602.000000  ...                   NaN                     NaN

[8 rows x 8 columns]
created_utc                 0
score                       0
domain                      0
id                          0
title                       0
author                     67
ups                         0
downs                       0
num_comments                0
permalink                   0
selftext                  330
link_flair_text           877
over_18                     0
thumbnail                   0
subreddit_id                0
edited                      0
link_flair_css_class      877
author_flair_css_class    877
is_self                     0
name                        0
url                         0
distinguished             855
dtype: int64

In [4]:
# Encode categorical variables
label_encoder = LabelEncoder()

if 'Gender' in df.columns:
    df['Gender'] = label_encoder.fit_transform(df['Gender'])

# Drop rows with missing values (or use fillna)
df = df.dropna()

In [6]:
df.columns = df.columns.str.strip()

In [11]:
print(df.columns)

Index(['created_utc', 'score', 'domain', 'id', 'title', 'author', 'ups',
       'downs', 'num_comments', 'permalink', 'selftext', 'link_flair_text',
       'over_18', 'thumbnail', 'subreddit_id', 'edited',
       'link_flair_css_class', 'author_flair_css_class', 'is_self', 'name',
       'url', 'distinguished'],
      dtype='str')

In [17]:
print(df.columns)

Index(['created_utc', 'score', 'domain', 'id', 'title', 'author', 'ups',
       'downs', 'num_comments', 'permalink', 'selftext', 'link_flair_text',
       'over_18', 'thumbnail', 'subreddit_id', 'edited',
       'link_flair_css_class', 'author_flair_css_class', 'is_self', 'name',
       'url', 'distinguished'],
      dtype='str')

In [22]:
df.head()

    created_utc  ...  distinguished
0  1.373374e+09  ...            NaN
1  1.350073e+09  ...            NaN
2  1.359465e+09  ...            NaN
3  1.323376e+09  ...            NaN
4  1.304022e+09  ...            NaN

[5 rows x 22 columns]

In [30]:
print(df.isna().sum())

created_utc                 0
score                       0
domain                      0
id                          0
title                       0
author                     67
ups                         0
downs                       0
num_comments                0
permalink                   0
selftext                  330
link_flair_text           877
over_18                     0
thumbnail                   0
subreddit_id                0
edited                      0
link_flair_css_class      877
author_flair_css_class    877
is_self                     0
name                        0
url                         0
distinguished             855
dtype: int64

In [32]:
print(locals())

{'__name__': '__main__', '__doc__': 'Automatically created module for IPython interactive environment', '__package__': None, '__loader__': None, '__spec__': None, '__builtin__': <module 'builtins' (built-in)>, '__builtins__': <module 'builtins' (built-in)>, '_ih': ['', '# Data handling\nimport pandas as pd\nimport numpy as np\n\n# Visualization\nimport matplotlib.pyplot as plt\nimport seaborn as sns\n\n# Preprocessing\nfrom sklearn.preprocessing import StandardScaler, LabelEncoder\nfrom sklearn.model_selection import train_test_split\n\n# Models\nfrom sklearn.linear_model import LogisticRegression\nfrom sklearn.cluster import KMeans\n\n# Evaluation\nfrom sklearn.metrics import accuracy_score, classification_report, confusion_matrix', '# Load dataset\ndf = pd.read_csv("AdvancedFitness.csv")\n\n# Preview\ndf.head()', 'print(df.info())\nprint(df.describe())\n\n# Check missing values\nprint(df.isnull().sum())', "# Encode categorical variables\nlabel_encoder = LabelEncoder()\n\nif 'Gender' in df.columns:\n    df['Gender'] = label_encoder.fit_transform(df['Gender'])\n\n# Drop rows with missing values (or use fillna)\ndf = df.dropna()", "# Assume target column is 'Fitness_Level'\nX = df.drop('Fitness_Level', axis=1)\ny = df['Fitness_Level']", 'df.columns = df.columns.str.strip()', 'scaler = StandardScaler()\n\nX_train_scaled = scaler.fit_transform(X_train)\nX_test_scaled = scaler.transform(X_test)', 'print(type(X_train))\nprint(X_train.shape)', 'from sklearn.preprocessing import StandardScaler\n\nscaler = StandardScaler()\n\nX_train_scaled = scaler.fit_transform(X_train)\nX_test_scaled = scaler.transform(X_test)', 'from sklearn.model_selection import train_test_split\n\n# Example\nX = df.drop("target", axis=1)\ny = df["target"]\n\nX_train, X_test, y_train, y_test = train_test_split(\n    X, y, test_size=0.2, random_state=42\n)', 'print(df.columns)', 'log_model = LogisticRegression()\nlog_model.fit(X_train_scaled, y_train)', 'print(X_train_scaled.shape)\nprint(y_train.shape)', '# 1. Imports\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.preprocessing import StandardScaler\nfrom sklearn.linear_model import LogisticRegression\n\n# 2. Split your data (make sure X and y already exist)\nX_train, X_test, y_train, y_test = train_test_split(\n    X, y, test_size=0.2, random_state=42\n)\n\n# 3. Scale the features\nscaler = StandardScaler()\nX_train_scaled = scaler.fit_transform(X_train)\nX_test_scaled = scaler.transform(X_test)\n\n# 4. Train Logistic Regression model\nlog_model = LogisticRegression()\nlog_model.fit(X_train_scaled, y_train)\n\n# 5. Check shapes (this will now work)\nprint(X_train_scaled.shape)\nprint(y_train.shape)', '# 0. Load data\nimport pandas as pd\ndf = pd.read_csv("AdvancedFitness.csv")\n\n# 1. Define X and y\nX = df.drop("target_column", axis=1)\ny = df["target_column"]\n\n# 2. Imports\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.preprocessing import StandardScaler\nfrom sklearn.linear_model import LogisticRegression\n\n# 3. Split\nX_train, X_test, y_train, y_test = train_test_split(\n    X, y, test_size=0.2, random_state=42\n)\n\n# 4. Scale\nscaler = StandardScaler()\nX_train_scaled = scaler.fit_transform(X_train)\nX_test_scaled = scaler.transform(X_test)\n\n# 5. Train model\nlog_model = LogisticRegression()\nlog_model.fit(X_train_scaled, y_train)\n\n# 6. Check\nprint(X_train_scaled.shape)\nprint(y_train.shape)', '# Load data\nimport pandas as pd\ndf = pd.read_csv("AdvancedFitness.csv")\n\n# Check columns FIRST\nprint(df.columns)\n\n# Define X and y (CHANGE TARGET HERE)\nX = df.drop("Workout_Frequency", axis=1)\ny = df["Workout_Frequency"]\n\n# Imports\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.preprocessing import StandardScaler\nfrom sklearn.linear_model import LogisticRegression\n\n# Split\nX_train, X_test, y_train, y_test = train_test_split(\n    X, y, test_size=0.2, random_state=42\n)\n\n# Scale\nscaler = StandardScaler()\nX_train_scaled = scaler.fit_transform(X_train)\nX_test_scaled = scaler.transform(X_test)\n\n# Train\nlog_model = LogisticRegression()\nlog_model.fit(X_train_scaled, y_train)\n\n# Check\nprint(X_train_scaled.shape)\nprint(y_train.shape)', 'print(df.columns)', 'y_pred = log_model.predict(X_test_scaled)\n\n# Accuracy\nprint("Accuracy:", accuracy_score(y_test, y_pred))\n\n# Report\nprint("\\nClassification Report:\\n", classification_report(y_test, y_pred))\n\n# Confusion Matrix\nsns.heatmap(confusion_matrix(y_test, y_pred), annot=True, fmt=\'d\')\nplt.title("Confusion Matrix")\nplt.show()', 'from sklearn.preprocessing import StandardScaler\n\nscaler = StandardScaler()\n\n# Fit on training data ONLY\nX_train_scaled = scaler.fit_transform(X_train)\n\n# Transform test data using SAME scaler\nX_test_scaled = scaler.transform(X_test)', '# Predict\ny_pred = log_model.predict(X_test_scaled)\n\n# Accuracy\nprint("Accuracy:", accuracy_score(y_test, y_pred))\n\n# Report\nprint("\\nClassification Report:\\n", classification_report(y_test, y_pred))\n\n# Confusion Matrix\nsns.heatmap(confusion_matrix(y_test, y_pred), annot=True, fmt=\'d\')\nplt.title("Confusion Matrix")\nplt.show()', 'scaler.fit_transform(X_test)  ', 'df.head()', 'wcss = []\n\nfor i in range(1, 11):\n    kmeans = KMeans(n_clusters=i, random_state=42)\n    kmeans.fit(X_train_scaled)\n    wcss.append(kmeans.inertia_)\n\nplt.plot(range(1, 11), wcss, marker=\'o\')\nplt.title("Elbow Method")\nplt.xlabel("Number of Clusters")\nplt.ylabel("WCSS")\nplt.show()', 'print(type(X_train_scaled))', 'kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)\nclusters = kmeans.fit_predict(X_train_scaled)\n\nprint(clusters[:10])', 'print(clusters[:10])', 'print(len(clusters))  # should match number of rows in X_train_scaled', 'kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)\nclusters = kmeans.fit_predict(X_train_scaled)\n\nprint(clusters[:10])\nprint(len(clusters))', '# Imports\nimport numpy as np\nimport pandas as pd\nfrom sklearn.preprocessing import StandardScaler\nfrom sklearn.cluster import KMeans\n\n# Example: make sure you already have your dataset loaded as df\n# If not, load it like:\n# df = pd.read_csv("your_file.csv")\n\n# Use numeric features\nX = df.select_dtypes(include=[np.number])\n\n# Scale the data\nscaler = StandardScaler()\nX_scaled = scaler.fit_transform(X)\n\n# Apply KMeans\nkmeans = KMeans(n_clusters=3, random_state=42, n_init=10)\nclusters = kmeans.fit_predict(X_scaled)\n\n# Output\nprint(clusters[:10])\nprint(len(clusters))', 'print(df.isna().sum())', 'plt.scatter(X_train_scaled[:, 0], X_train_scaled[:, 1], c=clusters, cmap=\'viridis\')\nplt.title("K-Means Clustering")\nplt.xlabel("Feature 1")\nplt.ylabel("Feature 2")\nplt.show()', 'print(locals())'], '_oh': {2:     created_utc  ...  distinguished
0  1.373374e+09  ...            NaN
1  1.350073e+09  ...            NaN
2  1.359465e+09  ...            NaN
3  1.323376e+09  ...            NaN
4  1.304022e+09  ...            NaN

[5 rows x 22 columns], 22:     created_utc  ...  distinguished
0  1.373374e+09  ...            NaN
1  1.350073e+09  ...            NaN
2  1.359465e+09  ...            NaN
3  1.323376e+09  ...            NaN
4  1.304022e+09  ...            NaN

[5 rows x 22 columns]}, '_dh': [PosixPath('/Users/adnanaltimeemy')], 'In': ['', '# Data handling\nimport pandas as pd\nimport numpy as np\n\n# Visualization\nimport matplotlib.pyplot as plt\nimport seaborn as sns\n\n# Preprocessing\nfrom sklearn.preprocessing import StandardScaler, LabelEncoder\nfrom sklearn.model_selection import train_test_split\n\n# Models\nfrom sklearn.linear_model import LogisticRegression\nfrom sklearn.cluster import KMeans\n\n# Evaluation\nfrom sklearn.metrics import accuracy_score, classification_report, confusion_matrix', '# Load dataset\ndf = pd.read_csv("AdvancedFitness.csv")\n\n# Preview\ndf.head()', 'print(df.info())\nprint(df.describe())\n\n# Check missing values\nprint(df.isnull().sum())', "# Encode categorical variables\nlabel_encoder = LabelEncoder()\n\nif 'Gender' in df.columns:\n    df['Gender'] = label_encoder.fit_transform(df['Gender'])\n\n# Drop rows with missing values (or use fillna)\ndf = df.dropna()", "# Assume target column is 'Fitness_Level'\nX = df.drop('Fitness_Level', axis=1)\ny = df['Fitness_Level']", 'df.columns = df.columns.str.strip()', 'scaler = StandardScaler()\n\nX_train_scaled = scaler.fit_transform(X_train)\nX_test_scaled = scaler.transform(X_test)', 'print(type(X_train))\nprint(X_train.shape)', 'from sklearn.preprocessing import StandardScaler\n\nscaler = StandardScaler()\n\nX_train_scaled = scaler.fit_transform(X_train)\nX_test_scaled = scaler.transform(X_test)', 'from sklearn.model_selection import train_test_split\n\n# Example\nX = df.drop("target", axis=1)\ny = df["target"]\n\nX_train, X_test, y_train, y_test = train_test_split(\n    X, y, test_size=0.2, random_state=42\n)', 'print(df.columns)', 'log_model = LogisticRegression()\nlog_model.fit(X_train_scaled, y_train)', 'print(X_train_scaled.shape)\nprint(y_train.shape)', '# 1. Imports\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.preprocessing import StandardScaler\nfrom sklearn.linear_model import LogisticRegression\n\n# 2. Split your data (make sure X and y already exist)\nX_train, X_test, y_train, y_test = train_test_split(\n    X, y, test_size=0.2, random_state=42\n)\n\n# 3. Scale the features\nscaler = StandardScaler()\nX_train_scaled = scaler.fit_transform(X_train)\nX_test_scaled = scaler.transform(X_test)\n\n# 4. Train Logistic Regression model\nlog_model = LogisticRegression()\nlog_model.fit(X_train_scaled, y_train)\n\n# 5. Check shapes (this will now work)\nprint(X_train_scaled.shape)\nprint(y_train.shape)', '# 0. Load data\nimport pandas as pd\ndf = pd.read_csv("AdvancedFitness.csv")\n\n# 1. Define X and y\nX = df.drop("target_column", axis=1)\ny = df["target_column"]\n\n# 2. Imports\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.preprocessing import StandardScaler\nfrom sklearn.linear_model import LogisticRegression\n\n# 3. Split\nX_train, X_test, y_train, y_test = train_test_split(\n    X, y, test_size=0.2, random_state=42\n)\n\n# 4. Scale\nscaler = StandardScaler()\nX_train_scaled = scaler.fit_transform(X_train)\nX_test_scaled = scaler.transform(X_test)\n\n# 5. Train model\nlog_model = LogisticRegression()\nlog_model.fit(X_train_scaled, y_train)\n\n# 6. Check\nprint(X_train_scaled.shape)\nprint(y_train.shape)', '# Load data\nimport pandas as pd\ndf = pd.read_csv("AdvancedFitness.csv")\n\n# Check columns FIRST\nprint(df.columns)\n\n# Define X and y (CHANGE TARGET HERE)\nX = df.drop("Workout_Frequency", axis=1)\ny = df["Workout_Frequency"]\n\n# Imports\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.preprocessing import StandardScaler\nfrom sklearn.linear_model import LogisticRegression\n\n# Split\nX_train, X_test, y_train, y_test = train_test_split(\n    X, y, test_size=0.2, random_state=42\n)\n\n# Scale\nscaler = StandardScaler()\nX_train_scaled = scaler.fit_transform(X_train)\nX_test_scaled = scaler.transform(X_test)\n\n# Train\nlog_model = LogisticRegression()\nlog_model.fit(X_train_scaled, y_train)\n\n# Check\nprint(X_train_scaled.shape)\nprint(y_train.shape)', 'print(df.columns)', 'y_pred = log_model.predict(X_test_scaled)\n\n# Accuracy\nprint("Accuracy:", accuracy_score(y_test, y_pred))\n\n# Report\nprint("\\nClassification Report:\\n", classification_report(y_test, y_pred))\n\n# Confusion Matrix\nsns.heatmap(confusion_matrix(y_test, y_pred), annot=True, fmt=\'d\')\nplt.title("Confusion Matrix")\nplt.show()', 'from sklearn.preprocessing import StandardScaler\n\nscaler = StandardScaler()\n\n# Fit on training data ONLY\nX_train_scaled = scaler.fit_transform(X_train)\n\n# Transform test data using SAME scaler\nX_test_scaled = scaler.transform(X_test)', '# Predict\ny_pred = log_model.predict(X_test_scaled)\n\n# Accuracy\nprint("Accuracy:", accuracy_score(y_test, y_pred))\n\n# Report\nprint("\\nClassification Report:\\n", classification_report(y_test, y_pred))\n\n# Confusion Matrix\nsns.heatmap(confusion_matrix(y_test, y_pred), annot=True, fmt=\'d\')\nplt.title("Confusion Matrix")\nplt.show()', 'scaler.fit_transform(X_test)  ', 'df.head()', 'wcss = []\n\nfor i in range(1, 11):\n    kmeans = KMeans(n_clusters=i, random_state=42)\n    kmeans.fit(X_train_scaled)\n    wcss.append(kmeans.inertia_)\n\nplt.plot(range(1, 11), wcss, marker=\'o\')\nplt.title("Elbow Method")\nplt.xlabel("Number of Clusters")\nplt.ylabel("WCSS")\nplt.show()', 'print(type(X_train_scaled))', 'kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)\nclusters = kmeans.fit_predict(X_train_scaled)\n\nprint(clusters[:10])', 'print(clusters[:10])', 'print(len(clusters))  # should match number of rows in X_train_scaled', 'kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)\nclusters = kmeans.fit_predict(X_train_scaled)\n\nprint(clusters[:10])\nprint(len(clusters))', '# Imports\nimport numpy as np\nimport pandas as pd\nfrom sklearn.preprocessing import StandardScaler\nfrom sklearn.cluster import KMeans\n\n# Example: make sure you already have your dataset loaded as df\n# If not, load it like:\n# df = pd.read_csv("your_file.csv")\n\n# Use numeric features\nX = df.select_dtypes(include=[np.number])\n\n# Scale the data\nscaler = StandardScaler()\nX_scaled = scaler.fit_transform(X)\n\n# Apply KMeans\nkmeans = KMeans(n_clusters=3, random_state=42, n_init=10)\nclusters = kmeans.fit_predict(X_scaled)\n\n# Output\nprint(clusters[:10])\nprint(len(clusters))', 'print(df.isna().sum())', 'plt.scatter(X_train_scaled[:, 0], X_train_scaled[:, 1], c=clusters, cmap=\'viridis\')\nplt.title("K-Means Clustering")\nplt.xlabel("Feature 1")\nplt.ylabel("Feature 2")\nplt.show()', 'print(locals())'], 'Out': {2:     created_utc  ...  distinguished
0  1.373374e+09  ...            NaN
1  1.350073e+09  ...            NaN
2  1.359465e+09  ...            NaN
3  1.323376e+09  ...            NaN
4  1.304022e+09  ...            NaN

[5 rows x 22 columns], 22:     created_utc  ...  distinguished
0  1.373374e+09  ...            NaN
1  1.350073e+09  ...            NaN
2  1.359465e+09  ...            NaN
3  1.323376e+09  ...            NaN
4  1.304022e+09  ...            NaN

[5 rows x 22 columns]}, 'get_ipython': <bound method InteractiveShell.get_ipython of <ipykernel.zmqshell.ZMQInteractiveShell object at 0x104099400>>, 'exit': <IPython.core.autocall.ZMQExitAutocall object at 0x104098470>, 'quit': <IPython.core.autocall.ZMQExitAutocall object at 0x104098470>, 'open': <function open at 0x103070b80>, '_':     created_utc  ...  distinguished
0  1.373374e+09  ...            NaN
1  1.350073e+09  ...            NaN
2  1.359465e+09  ...            NaN
3  1.323376e+09  ...            NaN
4  1.304022e+09  ...            NaN

[5 rows x 22 columns], '__':     created_utc  ...  distinguished
0  1.373374e+09  ...            NaN
1  1.350073e+09  ...            NaN
2  1.359465e+09  ...            NaN
3  1.323376e+09  ...            NaN
4  1.304022e+09  ...            NaN

[5 rows x 22 columns], '___': '', '__session__': '/Users/adnanaltimeemy/Untitled22.ipynb', '_i': 'plt.scatter(X_train_scaled[:, 0], X_train_scaled[:, 1], c=clusters, cmap=\'viridis\')\nplt.title("K-Means Clustering")\nplt.xlabel("Feature 1")\nplt.ylabel("Feature 2")\nplt.show()', '_ii': 'print(df.isna().sum())', '_iii': '# Imports\nimport numpy as np\nimport pandas as pd\nfrom sklearn.preprocessing import StandardScaler\nfrom sklearn.cluster import KMeans\n\n# Example: make sure you already have your dataset loaded as df\n# If not, load it like:\n# df = pd.read_csv("your_file.csv")\n\n# Use numeric features\nX = df.select_dtypes(include=[np.number])\n\n# Scale the data\nscaler = StandardScaler()\nX_scaled = scaler.fit_transform(X)\n\n# Apply KMeans\nkmeans = KMeans(n_clusters=3, random_state=42, n_init=10)\nclusters = kmeans.fit_predict(X_scaled)\n\n# Output\nprint(clusters[:10])\nprint(len(clusters))', '_i1': '# Data handling\nimport pandas as pd\nimport numpy as np\n\n# Visualization\nimport matplotlib.pyplot as plt\nimport seaborn as sns\n\n# Preprocessing\nfrom sklearn.preprocessing import StandardScaler, LabelEncoder\nfrom sklearn.model_selection import train_test_split\n\n# Models\nfrom sklearn.linear_model import LogisticRegression\nfrom sklearn.cluster import KMeans\n\n# Evaluation\nfrom sklearn.metrics import accuracy_score, classification_report, confusion_matrix', 'pd': <module 'pandas' from '/Users/adnanaltimeemy/miniconda3/envs/coding/lib/python3.12/site-packages/pandas/__init__.py'>, 'np': <module 'numpy' from '/Users/adnanaltimeemy/miniconda3/envs/coding/lib/python3.12/site-packages/numpy/__init__.py'>, 'plt': <module 'matplotlib.pyplot' from '/Users/adnanaltimeemy/miniconda3/envs/coding/lib/python3.12/site-packages/matplotlib/pyplot.py'>, 'sns': <module 'seaborn' from '/Users/adnanaltimeemy/miniconda3/envs/coding/lib/python3.12/site-packages/seaborn/__init__.py'>, 'StandardScaler': <class 'sklearn.preprocessing._data.StandardScaler'>, 'LabelEncoder': <class 'sklearn.preprocessing._label.LabelEncoder'>, 'train_test_split': <function train_test_split at 0x11e2f9800>, 'LogisticRegression': <class 'sklearn.linear_model._logistic.LogisticRegression'>, 'KMeans': <class 'sklearn.cluster._kmeans.KMeans'>, 'accuracy_score': <function accuracy_score at 0x10f853e20>, 'classification_report': <function classification_report at 0x10f875300>, 'confusion_matrix': <function confusion_matrix at 0x10f853f60>, '_i2': '# Load dataset\ndf = pd.read_csv("AdvancedFitness.csv")\n\n# Preview\ndf.head()', 'df':       created_utc  ...  distinguished
0    1.373374e+09  ...            NaN
1    1.350073e+09  ...            NaN
2    1.359465e+09  ...            NaN
3    1.323376e+09  ...            NaN
4    1.304022e+09  ...            NaN
..            ...  ...            ...
872  1.341513e+09  ...            NaN
873  1.340834e+09  ...            NaN
874  1.296068e+09  ...            NaN
875  1.352213e+09  ...            NaN
876  1.312401e+09  ...            NaN

[877 rows x 22 columns], '_2':     created_utc  ...  distinguished
0  1.373374e+09  ...            NaN
1  1.350073e+09  ...            NaN
2  1.359465e+09  ...            NaN
3  1.323376e+09  ...            NaN
4  1.304022e+09  ...            NaN


In [35]:
print(df.head())
print(df.columns)

    created_utc  ...  distinguished
0  1.373374e+09  ...            NaN
1  1.350073e+09  ...            NaN
2  1.359465e+09  ...            NaN
3  1.323376e+09  ...            NaN
4  1.304022e+09  ...            NaN

[5 rows x 22 columns]
Index(['created_utc', 'score', 'domain', 'id', 'title', 'author', 'ups',
       'downs', 'num_comments', 'permalink', 'selftext', 'link_flair_text',
       'over_18', 'thumbnail', 'subreddit_id', 'edited',
       'link_flair_css_class', 'author_flair_css_class', 'is_self', 'name',
       'url', 'distinguished'],
      dtype='str')