In [1]:
# Install if needed
!pip install pandas scikit-learn matplotlib seaborn nltk

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

nltk.download('punkt')
nltk.download('stopwords')

Requirement already satisfied: pandas in ./miniconda3/envs/coding/lib/python3.12/site-packages (3.0.1)
Requirement already satisfied: scikit-learn in ./miniconda3/envs/coding/lib/python3.12/site-packages (1.8.0)
Requirement already satisfied: matplotlib in ./miniconda3/envs/coding/lib/python3.12/site-packages (3.10.8)
Requirement already satisfied: seaborn in ./miniconda3/envs/coding/lib/python3.12/site-packages (0.13.2)
Requirement already satisfied: nltk in ./miniconda3/envs/coding/lib/python3.12/site-packages (3.9.2)
Requirement already satisfied: numpy>=1.26.0 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: scipy>=1.10.0 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: contourpy>=1.0.1 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from matplotlib) (12.1.1)
Requirement already satisfied: pyparsing>=3 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: click in ./miniconda3/envs/coding/lib/python3.12/site-packages (from nltk) (8.1.8)
Requirement already satisfied: regex>=2021.8.3 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from nltk) (2025.10.23)
Requirement already satisfied: tqdm in ./miniconda3/envs/coding/lib/python3.12/site-packages (from nltk) (4.67.1)
Requirement already satisfied: six>=1.5 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [2]:
# Load your dataset
df = pd.read_csv('consumos-combustibles-mensual.csv')

# Preview
df.head()

,Fecha,GLPs,Gasolinas,Querosenos,Gasoleos,Fueloleos
0,1969-01-01,133615.09620,166875.2129,123257.8090,401185.2939,912583.4202
1,1969-02-01,126748.47410,155466.8105,114682.5767,385360.0381,851877.8115
2,1969-03-01,107795.80910,184983.6699,109970.0796,418955.5808,873884.2933
3,1969-04-01,96683.15967,202319.8164,108797.9255,438975.5445,755490.1170
4,1969-05-01,79506.23804,206259.1523,103554.0784,467451.9469,729963.6009

In [4]:
print(df.columns)

Index(['Fecha', 'GLPs', 'Gasolinas', 'Querosenos', 'Gasoleos', 'Fueloleos'], dtype='str')

In [7]:
df.rename(columns={'Text': 'text'}, inplace=True)

In [9]:
print(df.columns)
print(df.head())

Index(['Fecha', 'GLPs', 'Gasolinas', 'Querosenos', 'Gasoleos', 'Fueloleos'], dtype='str')
       Fecha          GLPs    Gasolinas   Querosenos     Gasoleos    Fueloleos
0 1969-01-01  133615.09620  166875.2129  123257.8090  401185.2939  912583.4202
1 1969-02-01  126748.47410  155466.8105  114682.5767  385360.0381  851877.8115
2 1969-03-01  107795.80910  184983.6699  109970.0796  418955.5808  873884.2933
3 1969-04-01   96683.15967  202319.8164  108797.9255  438975.5445  755490.1170
4 1969-05-01   79506.23804  206259.1523  103554.0784  467451.9469  729963.6009

In [12]:
for col in df.columns:
    print(f"'{col}'")

'Fecha'
'GLPs'
'Gasolinas'
'Querosenos'
'Gasoleos'
'Fueloleos'

In [15]:
df.head()

       Fecha          GLPs    Gasolinas   Querosenos     Gasoleos    Fueloleos
0 1969-01-01  133615.09620  166875.2129  123257.8090  401185.2939  912583.4202
1 1969-02-01  126748.47410  155466.8105  114682.5767  385360.0381  851877.8115
2 1969-03-01  107795.80910  184983.6699  109970.0796  418955.5808  873884.2933
3 1969-04-01   96683.15967  202319.8164  108797.9255  438975.5445  755490.1170
4 1969-05-01   79506.23804  206259.1523  103554.0784  467451.9469  729963.6009

In [16]:
print(df.columns)

Index(['Fecha', 'GLPs', 'Gasolinas', 'Querosenos', 'Gasoleos', 'Fueloleos'], dtype='str')

In [19]:
print(df.columns)
print('cluster' in df.columns)

Index(['Fecha', 'GLPs', 'Gasolinas', 'Querosenos', 'Gasoleos', 'Fueloleos'], dtype='str')
False

In [21]:
print(df.head())

       Fecha          GLPs    Gasolinas   Querosenos     Gasoleos    Fueloleos
0 1969-01-01  133615.09620  166875.2129  123257.8090  401185.2939  912583.4202
1 1969-02-01  126748.47410  155466.8105  114682.5767  385360.0381  851877.8115
2 1969-03-01  107795.80910  184983.6699  109970.0796  418955.5808  873884.2933
3 1969-04-01   96683.15967  202319.8164  108797.9255  438975.5445  755490.1170
4 1969-05-01   79506.23804  206259.1523  103554.0784  467451.9469  729963.6009

In [22]:
df.to_csv('clustered_consumo_combustible.csv', index=False)