In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.cluster import KMeans
from sklearn.metrics import accuracy_score, classification_report
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("HybridAnimals.csv")
df.head()

,created_utc,score,domain,id,title,author,ups,downs,num_comments,permalink,...,over_18,thumbnail,subreddit_id,edited,link_flair_css_class,author_flair_css_class,is_self,name,url,distinguished
0,1.365855e+09,1048,i.imgur.com,1c9kdx,Killer Penguin,gyyp,1133,85,16,http://www.reddit.com/r/HybridAnimals/comments...,...,False,NaN,t5_2whve,False,NaN,NaN,False,t3_1c9kdx,http://i.imgur.com/5Z4Z5m5.jpg,NaN
1,1.372594e+09,850,i.imgur.com,1hd0pf,"By Request, a Gorilla/Elephant centaur: a Gori...",Asterix3791,962,112,23,http://www.reddit.com/r/HybridAnimals/comments...,...,False,NaN,t5_2whve,False,NaN,NaN,False,t3_1hd0pf,http://i.imgur.com/0UVkjnQ.jpg,NaN
2,1.364922e+09,697,i.imgur.com,1bixjd,The poisonous Mushroctopus,Felfriast,740,43,9,http://www.reddit.com/r/HybridAnimals/comments...,...,False,NaN,t5_2whve,False,NaN,NaN,False,t3_1bixjd,http://i.imgur.com/dTyg0eb.jpg,NaN
3,1.368039e+09,652,i.imgur.com,1dy542,Flamingophants,Yo-L,716,64,19,http://www.reddit.com/r/HybridAnimals/comments...,...,False,NaN,t5_2whve,False,NaN,NaN,False,t3_1dy542,http://i.imgur.com/uy81Bcb.jpg,NaN
4,1.362686e+09,635,i.imgur.com,19v46x,Here's a dragon (Satanic Leaf Tailed Gecko wit...,Felfriast,671,36,11,http://www.reddit.com/r/HybridAnimals/comments...,...,False,NaN,t5_2whve,False,NaN,NaN,False,t3_19v46x,http://i.imgur.com/I4V777F.jpg,NaN

In [4]:
for col in df.columns:
    print(repr(col))

'created_utc'
'score'
'domain'
'id'
'title'
'author'
'ups'
'downs'
'num_comments'
'permalink'
'selftext'
'link_flair_text'
'over_18'
'thumbnail'
'subreddit_id'
'edited'
'link_flair_css_class'
'author_flair_css_class'
'is_self'
'name'
'url'
'distinguished'

In [6]:
df.columns = df.columns.str.strip()

In [7]:
df.head()

,created_utc,score,domain,id,title,author,ups,downs,num_comments,permalink,...,over_18,thumbnail,subreddit_id,edited,link_flair_css_class,author_flair_css_class,is_self,name,url,distinguished
0,1.365855e+09,1048,i.imgur.com,1c9kdx,Killer Penguin,gyyp,1133,85,16,http://www.reddit.com/r/HybridAnimals/comments...,...,False,NaN,t5_2whve,False,NaN,NaN,False,t3_1c9kdx,http://i.imgur.com/5Z4Z5m5.jpg,NaN
1,1.372594e+09,850,i.imgur.com,1hd0pf,"By Request, a Gorilla/Elephant centaur: a Gori...",Asterix3791,962,112,23,http://www.reddit.com/r/HybridAnimals/comments...,...,False,NaN,t5_2whve,False,NaN,NaN,False,t3_1hd0pf,http://i.imgur.com/0UVkjnQ.jpg,NaN
2,1.364922e+09,697,i.imgur.com,1bixjd,The poisonous Mushroctopus,Felfriast,740,43,9,http://www.reddit.com/r/HybridAnimals/comments...,...,False,NaN,t5_2whve,False,NaN,NaN,False,t3_1bixjd,http://i.imgur.com/dTyg0eb.jpg,NaN
3,1.368039e+09,652,i.imgur.com,1dy542,Flamingophants,Yo-L,716,64,19,http://www.reddit.com/r/HybridAnimals/comments...,...,False,NaN,t5_2whve,False,NaN,NaN,False,t3_1dy542,http://i.imgur.com/uy81Bcb.jpg,NaN
4,1.362686e+09,635,i.imgur.com,19v46x,Here's a dragon (Satanic Leaf Tailed Gecko wit...,Felfriast,671,36,11,http://www.reddit.com/r/HybridAnimals/comments...,...,False,NaN,t5_2whve,False,NaN,NaN,False,t3_19v46x,http://i.imgur.com/I4V777F.jpg,NaN

In [16]:
print(df.columns.tolist())

['created_utc', 'score', 'domain', 'id', 'title', 'author', 'ups', 'downs', 'num_comments', 'permalink', 'selftext', 'link_flair_text', 'over_18', 'thumbnail', 'subreddit_id', 'edited', 'link_flair_css_class', 'author_flair_css_class', 'is_self', 'name', 'url', 'distinguished']

In [23]:

df.head()

,created_utc,score,domain,id,title,author,ups,downs,num_comments,permalink,...,over_18,thumbnail,subreddit_id,edited,link_flair_css_class,author_flair_css_class,is_self,name,url,distinguished
0,1.365855e+09,1048,i.imgur.com,1c9kdx,Killer Penguin,gyyp,1133,85,16,http://www.reddit.com/r/HybridAnimals/comments...,...,False,NaN,t5_2whve,False,NaN,NaN,False,t3_1c9kdx,http://i.imgur.com/5Z4Z5m5.jpg,NaN
1,1.372594e+09,850,i.imgur.com,1hd0pf,"By Request, a Gorilla/Elephant centaur: a Gori...",Asterix3791,962,112,23,http://www.reddit.com/r/HybridAnimals/comments...,...,False,NaN,t5_2whve,False,NaN,NaN,False,t3_1hd0pf,http://i.imgur.com/0UVkjnQ.jpg,NaN
2,1.364922e+09,697,i.imgur.com,1bixjd,The poisonous Mushroctopus,Felfriast,740,43,9,http://www.reddit.com/r/HybridAnimals/comments...,...,False,NaN,t5_2whve,False,NaN,NaN,False,t3_1bixjd,http://i.imgur.com/dTyg0eb.jpg,NaN
3,1.368039e+09,652,i.imgur.com,1dy542,Flamingophants,Yo-L,716,64,19,http://www.reddit.com/r/HybridAnimals/comments...,...,False,NaN,t5_2whve,False,NaN,NaN,False,t3_1dy542,http://i.imgur.com/uy81Bcb.jpg,NaN
4,1.362686e+09,635,i.imgur.com,19v46x,Here's a dragon (Satanic Leaf Tailed Gecko wit...,Felfriast,671,36,11,http://www.reddit.com/r/HybridAnimals/comments...,...,False,NaN,t5_2whve,False,NaN,NaN,False,t3_19v46x,http://i.imgur.com/I4V777F.jpg,NaN

In [24]:
print(df.columns)

Index(['created_utc', 'score', 'domain', 'id', 'title', 'author', 'ups',
       'downs', 'num_comments', 'permalink', 'selftext', 'link_flair_text',
       'over_18', 'thumbnail', 'subreddit_id', 'edited',
       'link_flair_css_class', 'author_flair_css_class', 'is_self', 'name',
       'url', 'distinguished'],
      dtype='str')